// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1_muT9vbPnGoPbu6ZYSBWrGNGzYfMHdo',
    appId: '1:1017051990999:android:6b0c94ecbb61379b7d1992',
    messagingSenderId: '1017051990999',
    projectId: 'void-of-course',
    storageBucket: 'void-of-course.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3He5wxHfuI541h9n2rkWb-UYhyeYJD_s',
    appId: '1:1017051990999:ios:bb09f0b89a56a0bd7d1992',
    messagingSenderId: '1017051990999',
    projectId: 'void-of-course',
    storageBucket: 'void-of-course.firebasestorage.app',
    iosBundleId: 'dev.lioluna.voidOfCourse',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_I4rorM9ZC_dFDesL7f4hUJkjeBvkIUk',
    appId: '1:1050821360970:web:89f5570f87d581cbfad5b3',
    messagingSenderId: '1050821360970',
    projectId: 'numerology-finder-a753c',
    authDomain: 'numerology-finder-a753c.firebaseapp.com',
    storageBucket: 'numerology-finder-a753c.firebasestorage.app',
    measurementId: 'G-5MB24WSYCN',
  );
}
